export const trends = [
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Adore', quantityPosts: '1,256 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Necessarily', quantityPosts: '4,796 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Let', quantityPosts: '2,238 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Astana', quantityPosts: '1,971 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Cool', quantityPosts: '24,8K posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'The most', quantityPosts: '99,4K posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: '#TikTok', quantityPosts: '123K posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Perhaps', quantityPosts: '3,256 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Travel', quantityPosts: '19,9K posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Happy Birthday', quantityPosts: '9,752 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'Kazhakhstan', quantityPosts: '4,515 posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: '#newmusic', quantityPosts: '14,3K posts'},
    {placeOfTrend: 'Trending in Kazakhstan', title: 'China', quantityPosts: '3,117 posts'},
]